### ISSUE TITLE
code question

### ISSUE THREAD

**Issue by cymqqqq** [sabarim/STEm-Seg#1]
can U explain 👍 
 self.conv_16 = nn.Conv3d(inter_channels[0] + inter_channels[1], inter_channels[1], 1, bias=False)
what's the meaning of inter_channels[0] + inter_channels[1]

**Comment by sabarim** [comment]
I hope that you are referring to embedding_decoder.py file. Here, the input to this convolutional layer is a concatenated feature map from self.block_32x and self.block_16x, where the output channels of these individual blocks are inter_channels[0] and inter_channels[1] respectively. The concatenation would make the number of input channels to the self.conv_16 layer to be inter_channels[0] + inter_channels[1]. Please refer to the function "forward" for a better understanding on this.

Also, the inter_channels list itself comes from the config file which is passed to the python program as a parameter. Please check stemseg/config/defaults.yaml for more details.

**Comment by cymqqqq** [comment]
thank you
