### ISSUE TITLE
dataset

### ISSUE THREAD

**Issue by linhaoqi027** [sabarim/STEm-Seg#12]
Could You please share the code that transform that DAVIS2017 dataset into a standard JSON format?

**Comment by Ali2500** [comment]
This code wasn't really saved somewhere. If you just look at how the JSON file is parsed in [data/generic_video_dataset_parser.py](https://github.com/sabarim/STEm-Seg/blob/master/stemseg/data/generic_video_dataset_parser.py) you can easily do it on your own. It's basically just a list of dicts (one per video sequence) with masks encoded in RLE format using pycocotools.
