### ISSUE TITLE
make dataset

### ISSUE THREAD

**Issue by luoww1992** [sabarim/STEm-Seg#14]
@Ali2500 
i will use YouTube-VIS dataset to do it.
i have make a new dataset like YouTube-VIS and i make the json file like its json file.
i have some questions when i make the last standard json file like youtube_vis_train.json you provide。
1, i don't know how to make the value: segmentations in youtube_vis_train.json from annotation['segmentations'] ?
2,are the keys: bboxes, areas useful?

**Comment by Ali2500** [comment]
1. The segmentation values are created using the mask to RLE encoding function in `pycocotools` (see `pycocotools.masktools.encode`)
2. I don't think the bboxes and areas are actually used.
