### ISSUE TITLE
No module named 'stemseg'

### ISSUE THREAD

**Issue by yunlongguo2000** [sabarim/STEm-Seg#17]
When I run "from stemseg.config import cfg", there is an error.

**Comment by dardirz** [comment]
did you find any answer?

**Comment by mfang2020** [comment]
I think this might be an environment variable issue. Exporting the right path would solve it.

**Comment by sabarim** [comment]
If you are using linux, try setting export PYTHONPATH=\<path to the stemseg source folder\>:$PYTHONPATH before running the code.
