### ISSUE TITLE
training convergence question

### ISSUE THREAD

**Issue by mfang2020** [sabarim/STEm-Seg#18]
First of all, thank you for sharing this great work! 

I was using the model to train on my own video data, and visualized the losses on tensorboard with the given Davis training config. It seems like all the losses wasn't converging at all, in fact, they just went up and down constantly.

I was wondering if you've seen this pattern in your training with Davis/YoutubeVIS or it converged just fine, and whether this is an attribute of the Lovasz hinge loss (I remember reading somewhere saying that Lovasz loss tends to be unstable). 
Please let me know, thank you so much!

**Comment by Ali2500** [comment]
Hi, sorry for the super-late response.

In case you're still interesting in knowing: the loss does indeed fluctuate quite a lot, but the overall trend (if you smooth out the loss values) still shows a reduction with several thousand iterations.

**Comment by sabarim** [comment]
Closing due to lack of further activity.
