### ISSUE TITLE
What is the main difference between MOTS and VIS Task?

### ISSUE THREAD

**Issue by Cyrus1993** [sabarim/STEm-Seg#24]
hello. I hope you are well.
I know MOTS task definition is multi-object tracking and segmentation.
In addition, I know (from what I understood) that the video instance segmentation task does exactly that.
In both tasks, we are interested in segmenting and tracking instances in videos.
So, what exactly is the difference between these two tasks?

**Comment by Ali2500** [comment]
The underlying task is identical. The only difference is in the evaluation metric (sMOTSA for MOTS, mAP for YTVIS) )and the type of data (driving scenes for MOTS, youtube videos for YTVIS).

**Comment by Cyrus1993** [comment]
Thank you very much for your response. I have read your article many times as well as other articles in this field. I can say that less research with this level of delicacy and detail has shed light on all the issues in this field. Thank you for publishing your research.
