### ISSUE TITLE
Could you provide the pretrained model which uses ResNet-50 as backbone? 

### ISSUE THREAD

**Issue by OasisYang** [sabarim/STEm-Seg#3]
Hi, thanks for releasing the codes. I'm trying to use your work as a baseline model, however due to the lack of computational resources, I want to start from the model whose backbone is resnet50. And the released pre-trained STEM-Seg is based on R-101, could you also release the model with R-50?
Thanks a lot!

**Comment by Ali2500** [comment]
Hi, if you're referring to the pretrained backbone network that is used to start the training from, then this has been addressed in #2
