### ISSUE TITLE
I just got 28.66 score with the trained model checkpoints you gave

### ISSUE THREAD

**Issue by EDENpraseHAZARD** [sabarim/STEm-Seg#4]
Hi, thanks for releasing the codes. I'm trying to inference the model in Youtube-VIS dataset with the trained model checkpoints you gave.
<img width="875" alt="屏幕快照 2020-11-10 16 17 58" src="https://user-images.githubusercontent.com/53077461/98648074-bed6f580-2370-11eb-8573-d6043b927c60.png">

But I just got 0.286648836.
<img width="865" alt="屏幕快照 2020-11-10 16 22 34" src="https://user-images.githubusercontent.com/53077461/98648431-3f95f180-2371-11eb-841c-f6857700c42c.png">
The command I used is :
`python stemseg/inference/main.py /gdata/gaoyuan/STEm-Seg/model/author/youtube_vis.pth -o /gdata/gaoyuan/STEm-Seg/model/author/out_test --dataset ytvis --resize_embeddings`
I don't know why I can't get 34.6 as mentioned in your paper.

**Comment by Ali2500** [comment]
Hi, this is quite strange. We ran the code on multiple PyTorch versions and got the same result. I'm not sure how this can be debugged though.

**Comment by mitclose** [comment]
how to use result.json to get AP?  I always meet problems when I use cocoapi

**Comment by Ali2500** [comment]
> how to use result.json to get AP? I always meet problems when I use cocoapi

You have to zip the json file and upload it to the evaluation server on CodaLab.

**Comment by lucasjinreal** [comment]
@Ali2500 Hi, is this model training must needed squence images? How did u train on coco?
