### ISSUE TITLE
What is the fastest way to make inference on rnadom videos?

### ISSUE THREAD

**Issue by asrlhhh** [sabarim/STEm-Seg#9]
I know there is a short paragraph saying how to extend test on other datasets. But the current code structure ask for json file, which contains annotations, for each dataset. I guess it 's used for evaluation of some quant metrics on those conventional datasets. I am wondering if there is a way to make inference on raw video input without that json file. The **sequence** object in the code is hard to be dissected.

**Comment by Ali2500** [comment]
Actually the JSON file associated with each dataset isn't for calculating metrics, but contains the actual annotations (segmentation masks) as RLE encoded text and also the category labels (wherever applicable). The easiest way would be to create a JSON file in a similar format for whatever dataset you want to evaluate.

At a high level, this JSON file contains a list of sequences. Each sequence is a dict with an `image_paths` key (list of relative paths to the video frames) and a `segmentations` key (nested list: outer list indexes the video frames and inner list indexes the object instances).

**Comment by mfang2020** [comment]
> I know there is a short paragraph saying how to extend test on other datasets. But the current code structure ask for json file, which contains annotations, for each dataset. I guess it 's used for evaluation of some quant metrics on those conventional datasets. I am wondering if there is a way to make inference on raw video input without that json file. The **sequence** object in the code is hard to be dissected.

Hi there! I encounter the same problem as you did, namely infer on a random video sequence without the ground truth annotations. I was wondering if you've found a way to do so. I'd really appreciate some pointers! Thank you!
